name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress runTests
        uses: cypress-io/github-action@v5
        with:
          test: npm run test
          wait-on: "http://localhost:8080"
