name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          start: |
            npm i
            npm run dev

      - name: Cypress runTests
        uses: cypress-io/github-action@v5
