name: Cypress Tests

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress runTests
        uses: cypress-io/github-action@v5
        with:
          start: |
            npm i
            npm run dev
            npm run test
